services:
  - type: web
    name: songify-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn core.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: PYTHON_VERSION
        value: 3.11.8
    autoDeploy: true
