services:
  - type: web
    name: songify-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn SONG_MANAGER_DJANGO_BACKEND.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: SONG_MANAGER_DJANGO_BACKEND.settings
      - key: PYTHON_VERSION
        value: 3.11.8
