# Generated by Django 5.1.7 on 2025-07-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('album', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.PositiveIntegerField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
            ],
        ),
    ]
